version: "3"
services:
  ######## DATABASE ########
  mysql:
    container_name: mysql
    image: mysql:8
    ports:
    - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root 
      MYSQL_DATABASE: app             
      MYSQL_USER: app_user               
      MYSQL_PASSWORD: test1234
    networks:
    - web_app_challenge
    restart: on-failure

networks:
  web_app_challenge:
    driver: bridge

